#!/usr/bin/env bash
# =============================================================================
# PersianUltraDNS — client builder (Linux / macOS)
#
# Installs Rust if needed, builds pud-client, asks for the tunnel domain(s),
# the pre-shared key, and resolvers, writes client_config.toml, and prints how
# to run it. Exposes a local SOCKS5 proxy and an HTTP CONNECT proxy.
#
# Usage:  bash build_client.sh
# =============================================================================
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/yourname/PersianUltraDNS.git}"
SOCKS_LISTEN="${SOCKS_LISTEN:-127.0.0.1:18080}"
HTTP_LISTEN="${HTTP_LISTEN:-127.0.0.1:18081}"
MAX_RESPONSE="${MAX_RESPONSE:-1232}"

c_green=$'\033[0;32m'; c_red=$'\033[0;31m'; c_yellow=$'\033[1;33m'
c_cyan=$'\033[0;36m';  c_reset=$'\033[0m'
info()  { echo "${c_cyan}[*]${c_reset} $*"; }
ok()    { echo "${c_green}[+]${c_reset} $*"; }
warn()  { echo "${c_yellow}[!]${c_reset} $*"; }
die()   { echo "${c_red}[x]${c_reset} $*" >&2; exit 1; }

# --- Rust toolchain ----------------------------------------------------------
if ! command -v cargo >/dev/null 2>&1; then
  info "Rust not found; installing via rustup..."
  command -v curl >/dev/null 2>&1 || die "curl is required to install Rust."
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi
# shellcheck disable=SC1091
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"
command -v cargo >/dev/null 2>&1 || die "cargo not on PATH; open a new shell and re-run."
ok "Rust toolchain ready: $(cargo --version)"

# --- Locate / fetch the source -----------------------------------------------
if [ -f "Cargo.toml" ] && grep -q "pud-client" Cargo.toml 2>/dev/null; then
  SRC_DIR="$(pwd)"
else
  SRC_DIR="${SRC_DIR:-$(pwd)/PersianUltraDNS}"
  if [ ! -d "$SRC_DIR/.git" ] && [ ! -f "$SRC_DIR/Cargo.toml" ]; then
    info "Cloning $REPO_URL ..."
    git clone --depth 1 "$REPO_URL" "$SRC_DIR"
  fi
fi
if [ ! -f "$SRC_DIR/Cargo.toml" ] || ! grep -q "pud-client" "$SRC_DIR/Cargo.toml" 2>/dev/null; then
  found="$(find "$SRC_DIR" -maxdepth 3 -name Cargo.toml -exec grep -l 'pud-client' {} \; 2>/dev/null | head -n1 || true)"
  [ -n "$found" ] && SRC_DIR="$(dirname "$found")"
fi
[ -f "$SRC_DIR/Cargo.toml" ] || die "Could not find the PersianUltraDNS workspace."
ok "Workspace: $SRC_DIR"

# --- Build -------------------------------------------------------------------
info "Building pud-client (release)... this can take a few minutes."
( cd "$SRC_DIR" && cargo build --release -p pud-client )
BIN="$SRC_DIR/target/release/pud-client"
[ -x "$BIN" ] || die "Build did not produce $BIN"
ok "Built: $BIN"

# --- Collect settings --------------------------------------------------------
echo
echo "Enter the SAME tunnel domain(s) configured on the server."
read -r -p "Domain(s) (comma/space separated): " DOMAIN_INPUT
[ -n "${DOMAIN_INPUT// /}" ] || die "At least one domain is required."

echo
echo "Paste the PRE-SHARED KEY shown by the server installer (hex)."
read -r -p "Key (hex): " KEY_HEX
[ -n "${KEY_HEX// /}" ] || die "The key is required."

echo
echo "Resolvers to send tunnel queries through."
echo "  - Comma/space separated. Accepts IP, IP:port, CIDR, CIDR:port."
echo "  - Press Enter to use sensible defaults (8.8.8.8, 1.1.1.1, 9.9.9.9)."
read -r -p "Resolvers: " RESOLVER_INPUT
[ -n "${RESOLVER_INPUT// /}" ] || RESOLVER_INPUT="8.8.8.8, 1.1.1.1, 9.9.9.9"

# Build TOML arrays.
to_toml_array() {
  local out="[" first=1 x
  for x in $(echo "$1" | tr ',' ' '); do
    x="$(echo "$x" | xargs)"; [ -z "$x" ] && continue
    if [ $first -eq 1 ]; then first=0; else out+=", "; fi
    out+="\"$x\""
  done
  echo "$out]"
}
DOMAINS_TOML="$(to_toml_array "$DOMAIN_INPUT")"
RESOLVERS_TOML="$(to_toml_array "$RESOLVER_INPUT")"
FIRST_DOMAIN="$(echo "$DOMAIN_INPUT" | tr ',' ' ' | awk '{print $1}')"

# --- Write config ------------------------------------------------------------
CONF_FILE="$SRC_DIR/client_config.toml"
cat > "$CONF_FILE" <<EOF
# PersianUltraDNS client config (generated by build_client.sh)
socks_listen = "$SOCKS_LISTEN"
http_listen  = "$HTTP_LISTEN"
domain = "$FIRST_DOMAIN"
domains = $DOMAINS_TOML
key_hex = "$KEY_HEX"
resolvers = $RESOLVERS_TOML
resolvers_file = ""
max_response = $MAX_RESPONSE
in_flight = 8
idle_poll_ms = 60
query_timeout_ms = 4000
max_uplink_chunk = 1024
log_level = "info"
EOF
ok "Wrote config: $CONF_FILE"

# --- Report ------------------------------------------------------------------
echo
echo "============================================================"
echo "${c_green}  CLIENT READY${c_reset}"
echo "============================================================"
echo "  Run it:"
echo "    ${c_cyan}$BIN --config $CONF_FILE${c_reset}"
echo
echo "  Point apps at one of:"
echo "    SOCKS5 proxy : ${c_cyan}$SOCKS_LISTEN${c_reset}   (browsers, proxychains: socks5h://$SOCKS_LISTEN)"
echo "    HTTP  proxy  : ${c_cyan}$HTTP_LISTEN${c_reset}   (HTTP CONNECT; for HTTPS/any TCP)"
echo
echo "  Tip: in your browser enable 'proxy DNS over SOCKS' to avoid DNS leaks."
echo "============================================================"
